### ISSUE TITLE
PROYECTO FINAL

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-final-proyecto-final-topicos_a-4bs-idm#1]
EQUIPO:
Diego Cruz Cruz
Irvin Jiménez Sánchez
Marco Uriel Rosas García

[PROYECTO FINAL_ Topicos avanzados de programacion.pdf](https://github.com/SistemasTecTlaxiaco/actividad-final-proyecto-final-topicos_a-4bs-idm/files/15479746/PROYECTO.FINAL_.Topicos.avanzados.de.programacion.pdf)

**Comment by josealfredo79** [comment]
Muy bien felicidades...
